config/routes.rb
Rails.application.routes.draw do
  resources :arts
  resources :albums
  resources :users
  root 'pages#index'
  get 'contact' => 'pages#contact'
  get 'originals' => 'arts#show'
  get 'signup'  => 'users#new' 
   get '/login' => 'sessions#new'
   post 'login' => 'sessions#create'
   delete 'logout' => 'sessions#destroy'
  

end

app/models/album.rb
class Album < ActiveRecord::Base
	has_many :arts
end

app/models/art.rb
class Art < ActiveRecord::Base

	mount_uploader :image, ImageUploader
		belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password 
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	  def index
    @albums = Album.all
  end 

  def show
    @album = Album.find( params[:id])
    @arts = @album.arts
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user 

def current_user 
  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
end
def require_user 
  redirect_to '/login' unless current_user 
end

end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  
  before_action :set_art, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:index, :show]


  # GET /arts
  # GET /arts.json
  def index
    @arts = Art.all
  end

  # GET /arts/1
  # GET /arts/1.json
  def show
     @art = Art.find( params[:id])
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts
  # POST /arts.json
    def upload
    @album = Album.find( params[:album_id])
  end
  
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to @art, notice: 'Art was successfully created.' }
        format.json { render :show, status: :created, location: @art.file.album.url }
      else
        format.html { render :new }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1
  # PATCH/PUT /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to @art, notice: 'Art was successfully updated.' }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1
  # DELETE /arts/1.json
  def destroy
    @art.destroy
    respond_to do |format|
      format.html { redirect_to arts_url, notice: 'Art was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_params
      params.require(:art).permit(:name, :description, :image, :title, :album_id)
    end
      def set_album
    @album = Album.find params[:album_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new 
end
def create
  @user = User.find_by_email(params[:session][:email])
  if @user && @user.authenticate(params[:session][:password])
    session[:user_id] = @user.id
    redirect_to '/'
  else
    redirect_to '/login'
  end 
end
def destroy 
  session[:user_id] = nil 
  redirect_to '/' 
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
  @user = User.new
end
def create 
  @user = User.new(user_params) 
  if @user.save 
    session[:user_id] = @user.id 
    redirect_to '/' 
  else 
    redirect_to '/signup' 
  end 
end
	
private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<div class="albums">
  <div class="container">

    <div class="row">
      <% @albums.each do |album|%> 
        <div class="item col-md-4">
          <div class="img-container">
            <%= image_tag album.image %>
          </div>
          <div class="album-info">
            <h2><%= album.title %></h2> 
            <p><%= link_to "See Album", album_path(album) %></p>
          </div>
        </div>
      <% end %> 
    </div>

  </div>
</div>

app/views/albums/show.html.erb
<head>     <link rel="stylesheet" href="https://blueimp.github.io/Gallery/css/blueimp-gallery.min.css"></head>
<p id="notice"><%= notice %></p>

<div class="photos">
  <div class="container">
			<!--Start imgs links -->
				<div id="links">
					<div class="row">
					<% @album.arts.each do |art|%> 
						<div class="col-md-3">
				    		<a class="img-rounded" href="<%= art.image.url %>" title="<%= art.name %>" data-gallery>
        					<img class="img-responsive img-rounded" src="<%= art.image.thumb.url %>" alt="<%= art.name %>">
    						</a>
						</div>	
						      <% end %> 
				</div>
			</div>
		</div>
	</div>
		<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls"data-use-bootstrap-modal="false">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<script src="js/bootstrap-image-gallery.min.js"></script>

app/views/arts/_form.html.erb
    <div class="new-form">
<%= form_for @art, html: { multipart: true }  do |f| %>
  <% if @art.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@art.errors.count, "error") %> prohibited this art from being saved:</h2>

      <ul>
      <% @art.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
    <div class="field">
    <%= f.label :album %><br>
    <%= f.collection_select  :album_id, Album.order(:title, ),:id,:title, include_blank: false, :class => "gall-select" %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, multiple: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/arts/edit.html.erb
<h1>Editing Art</h1>

<%= render 'form' %>

<%= link_to 'Show', @art %> |
<%= link_to 'Back', arts_path %>

app/views/arts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="gallist">
<h1>Gallery Listings</h1>

  <div class="row">
    <% @arts.each do |art| %>
    <div class= "col-md-4">
      <ul>
        <li><%= art.name %></li>
        <li><%= art.description %></li>
        <li><%= image_tag art.image.thumb.url %></li>
        <li><%= link_to 'Show', art %></li>
        <li><%= link_to 'Edit', edit_art_path(art) %></li>
        <li><%= link_to 'Destroy', art, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
      </div>
    <% end %>
    </div>

<br>

<%= link_to 'Add to Gallery', new_art_path %>
</div>

app/views/arts/new.html.erb
<div class="new-form">
<h1>Add to Gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', arts_path %>
</div>

app/views/arts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @art.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @art.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @art.image.thumb.url %>
</p>

<p>


<%= link_to 'Edit', edit_art_path(@art) %> |
<%= link_to 'Back', arts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mattison Photography</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Stint+Ultra+Condensed' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Six+Caps' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Rajdhani:700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="css/bootstrap-image-gallery.min.css">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

</head>
<body>
<!-- Header and nav bar -->
	<div class="header">
		<div class="container">
			<div class="row">
				<div class="col-md-5 col-sm-5">
					<h1>Mattison.Greff</h1>
				</div>
				<div class="col-md-7 col-sm-7">
					<ul class ="pull-right">
						<li><%= link_to "Home", root_path%></li>
							<li><a href="/albums/1">Portraits</a></li>
							<li><a href="/albums/2">Weddings</a></li>
							<li><a href="/albums/3">Prints and Artistic</a></li>
						<li><%= link_to "Contact", contact_path%>
					</ul>
				</div>
			</div>
		</div>
	</div>
<!--Body -->
<%= yield %>


<!--Scrips for bootstrap and drop down menu -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<!--Footer-->
<div class="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-2">

				<!--Login stuff-->
				<div class="login">
				<% if current_user %> 
  					<ul>  
    					<li><%= link_to "Log out", logout_path, method: "delete" %></li> 
    					<li><%= link_to "Edit Gallery", arts_path%></li>
  					</ul> 
				<% else %> 
  					<ul> 
    					<li><%= link_to "Login", "/login" %></a></li> 
    					<li><%= link_to "Signup", 'signup' %></a></li> 
  					</ul> 
				<% end %>
				</div>
			</div>
			<div class="col-md-10">
				<ul class="pull-right">
					<li><%= link_to image_tag('google-plus.png', :size => '40x40'), "https://www.google.ca" %></li>
					<li><%= link_to image_tag('instagram.png', :size => '40x40'), "https://www.instagram.com/___moogs/" %></li>
					<li><%= link_to image_tag('flickr.png', :size => '40x40'), "https://www.flickr.com/photos/morgangreff/" %></li>
					<li><%= link_to image_tag('twitter.png', :size => '40x40'), "https://www.google.ca" %></li>
				</ul>
			</div>
		</div>
	</div>
</div>
</body>
</html>

app/views/pages/biography.html.erb
<div class="biography">
	<div class="container">
		<div class="row">
			<div class="col-md-6 pull-left">
				<h3>Biography</h3>
				<p>Brett Heidi grew up in the Calgary to Olds area of Alberta.  She experienced both city and farm life in a family who was thoroughly involved in art.  She says "I have always had a passion for the use of colour in reflecting light. It is especially exciting to complete a project that emphasizes my own appreciation for the subject."  She feels that art is like music, but to the eye, life's beautiful things put onto canvas tells a story and affects our emotions.</p>
				<p>In her 20's Brett had the opportunity to live in Mazatlan, Mexico and while living there, married her husband, and had the opportunity to be immersed in local culture as well as discover parts of central Mexico.  They now live in Olds, Alberta where she continues to paint and reach out for new opportunities.</p>
				<p>Brett Heidi has experience with painting in oil and watercolour but recently prefers acrylic.  She has been commissioned to sketch portraits since 2001 and also does custom paintings.</p>
			</div>
			<div class="col-md-6 pull-right center">
				<%= image_tag 'brett.jpg', :class => "pull-center" %>
			</div>
		</div>
	</div>
</div>

app/views/pages/index.html.erb
<head>
     <link rel="stylesheet" href="https://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
     <link rel="stylesheet" type="text/css" href="slick.css"/>
<link rel="stylesheet" type="text/css" href="slick-theme.css"/>

</head>
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-8 words">
          <h2>About Me and my goals</h2>
          <p>   It wasn’t until my early 20’s that I realized what I really wanted to do in life was photography. I found a job with a commercial photography outfit which did everything; editorial, commercial, advertising, copying, portrait photography. We also made giant prints and offered drymounting and wetmounting services. We worked with line film, continuous tone, and produced half-tones.During these years I took night courses at University where I discovered the artistic side of the craft. What an education!</p>
        </div>
        
        <div class="col-md-6 col-sm-4">
        <!--JS slde stuff-->
            <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
          <script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
          <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.slick/1.5.9/slick.min.js"></script>
            <script type="text/javascript">
          $(function(){
            $('.your-class').slick({
              
            arrows: false,
              dots: true,
                infinite: true,
            speed: 500,
            fade: true,
            cssEase: 'linear'

              });
          });

            </script>
          <div class="your-class">
            <div><%= image_tag "about1", :class=> "middle img-rounded"%></div>
            <div>your content</div>
            <div>your content</div>
          </div>



        </div>
      </div>
    </div>
  </div>

app/views/pages/originals.html.erb
<head>
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<link rel="stylesheet" href="bootstrap-image-gallery.min.css">
</head>

<div class="originals">

<!--Start imgs links -->
	<div id="links">
		<div class="row">
		<% @arts.each do |t| %>
			<div class="col-md-4">
			<%= link_to image_tag('t.image.thumb.url'), "t.image", data-gallery%>
				<a href="imgs/wedding/wedding1.jpg" title="Zack & Iryna 2015" data-gallery>
        			<img class="img-responsive img-rounded" src="imgs/wedding/thumbnail/wedding1.jpg" alt="Zack & Iryna 2015">
    			</a>
			</div>	
			<%end%>
		</div>
	</div>

<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls"data-use-bootstrap-modal="false">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
</div>

app/views/pages/show.html.erb
<div class="photos">
  <div class="container">

    <h1><%= @album.title %></h1>
    <div class="row">
      <% @arts.each do |art|%> 
        <div class="item col-md-4">
          <div class="img-container">
            <%= image_tag art.image %>
          </div>
          <div class="photo-info">
            <p><%= art.description %></p> 
          </div>
        </div>
      <% end %> 
    </div>

  </div>
</div>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>

  
    </div>
  </div>
</div>